[package]
name = "general_pvs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"

[dependencies]
byteorder = "1"
chrono = "0.4.3"
rand = "0.8.5"
