name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        build: [release]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: get rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: cargo build
        run: cargo build --profile ${{ matrix.build }} --all-features --all-targets
      - name: tests
        run: cargo test
