name: build
on: [push]
jobs:
  build:
    strategy:
      matrix:
        build: [release]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: get rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile ${{ matrix.build }} --all-features
      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
